import { Boss } from './bossGreen.js';
import { saveScore } from './leaderboard.js';
const query = (...selectors) => selectors.map(selector => document.querySelector(selector)).find(Boolean);

export class Game {
  constructor({ camera, audio, playerName, onEnd }) {
    this.camera = camera; this.audio = audio; this.playerName = playerName || 'PLAYER'; this.onEnd = onEnd;
    this.canvas = document.querySelector('#game-canvas'); this.ctx = this.canvas.getContext('2d');
    this.screen = query('#screen-game', '#game-screen'); this.running = false; this.paused = false;
    this.last = 0; this.countdown = 3; this.lives = 3; this.score = 0; this.hits = 0; this.shots = 0; this.gazeState = 'UNKNOWN';
    this.combo = 0; this.bestCombo = 0; this.cooldown = 0; this.penaltyCooldown = 0;
    this.projectiles = []; this.particles = []; this.bossProjectiles = []; this.boss = null;
    this.mouse = { x: 0, y: 0 }; this.fire = this.fire.bind(this); this.move = this.move.bind(this); this.resize = this.resize.bind(this);
  }
  start() { this.resize(); this.boss = new Boss(this.canvas.width, this.canvas.height); this.mouse = { x: this.canvas.width * .5, y: this.canvas.height * .5 }; this.countdown = 3; this.last = performance.now(); this.running = true; this.canvas.addEventListener('mousemove', this.move); window.addEventListener('keydown', this.fire); window.addEventListener('resize', this.resize); query('#pause-button','#pause-btn')?.addEventListener('click', () => this.pause()); query('#sound-button','#sound-btn')?.addEventListener('click', () => { const button=query('#sound-button','#sound-btn'); const on = this.audio.toggle(); if(button) button.textContent = on ? '🔊 SOUND ON' : '🔇 SOUND OFF'; }); requestAnimationFrame(this.loop.bind(this)); }
  resize() { this.canvas.width = this.screen.clientWidth; this.canvas.height = this.screen.clientHeight; if (this.boss) { this.boss.x = Math.min(this.boss.x, this.canvas.width - 60); this.boss.y = Math.min(this.boss.y, this.canvas.height - 55); } }
  move(event) { const rect = this.canvas.getBoundingClientRect(); this.mouse = { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
  fire(event) { if (event.code !== 'Space' || event.repeat || !this.running || this.paused || this.countdown > 0 || this.cooldown > 0) return; event.preventDefault(); this.shots++; this.cooldown = .16; this.audio.play('shoot'); if (this.gazeState === 'AWAY' && this.boss.cover <= 0) this.hitBoss(); }
  pause() { this.paused = true; query('#screen-pause','#pause-screen')?.classList.add('active'); }
  resume() { this.paused = false; query('#screen-pause','#pause-screen')?.classList.remove('active'); this.last = performance.now(); }
  loop(now) { if (!this.running) return; const dt = Math.min(.04, (now - this.last) / 1000 || 0); this.last = now; if (!this.paused) { if (this.countdown > 0) { this.countdown = Math.max(0, this.countdown - dt); this.showCountdown(); } else this.update(dt, now); } this.draw(); requestAnimationFrame(this.loop.bind(this)); }
  showCountdown() { const element = query('#game-message','#status-banner'); if (!element) return; if (this.countdown > 0) { element.textContent = String(Math.ceil(this.countdown)); element.classList.add('show'); element.style.opacity = '1'; } else { element.textContent = 'LOOK AWAY... FIRE!'; element.style.opacity = ''; element.classList.remove('show'); void element.offsetWidth; element.classList.add('show'); } }
  update(dt, now) {
    this.cooldown = Math.max(0, this.cooldown - dt); this.penaltyCooldown = Math.max(0, this.penaltyCooldown - dt);
    const gaze = this.camera.state(now); this.gazeState = gaze.state; this.updateHud(gaze);
    if (gaze.state === 'LOOKING' && this.penaltyCooldown <= 0) { this.penaltyCooldown = 2.2; this.loseLife('STOP LOOKING AT ME!!!'); this.boss.cover = 1.25; }
    this.boss.update(dt, this.canvas.width, this.canvas.height, gaze.state === 'LOOKING', this.mouse.x, this.mouse.y);
    if (Math.random() < dt * 3.6) this.bossProjectiles.push({ x: this.boss.x, y: this.boss.y, vx: (this.mouse.x - this.boss.x) * 2, vy: (this.mouse.y - this.boss.y) * 2 });
    for (const projectile of this.bossProjectiles) { projectile.x += projectile.vx * dt; projectile.y += projectile.vy * dt; if (Math.hypot(projectile.x - this.mouse.x, projectile.y - this.mouse.y) < 28) { projectile.dead = true; this.loseLife('THE BOSS GOT YOU.'); } }
    this.bossProjectiles = this.bossProjectiles.filter(projectile => !projectile.dead && projectile.x > -220 && projectile.x < this.canvas.width + 220 && projectile.y > -220 && projectile.y < this.canvas.height + 220);
    this.particles.forEach(particle => { particle.x += particle.vx * dt; particle.y += particle.vy * dt; particle.life -= dt; }); this.particles = this.particles.filter(particle => particle.life > 0);
    if (this.boss.hp <= 0) this.finish(true, 'YOU BEAT HIM WITHOUT LOOKING.');
  }
  loseLife(message) { if (this.penaltyCooldown > 0 && message.startsWith('STOP')) return; this.lives--; this.combo = 0; this.audio.play('damage'); this.message(message); this.shake(); if (this.lives <= 0) this.finish(false, message); }
  hitBoss() { if (this.boss.cover > 0) return; const critical = Math.random() < .12; this.boss.hit(); this.hits++; this.combo++; this.bestCombo = Math.max(this.bestCombo, this.combo); this.score += critical ? 250 : 100; this.audio.play(critical ? 'critical' : 'hit'); this.burst(this.boss.x, this.boss.y, critical ? '#ffd447' : '#f64d76'); this.message(critical ? 'CRITICAL!' : 'BOSS HIT!'); this.shake(); }
  finish(won, reason) { this.running = false; this.audio.play(won ? 'victory' : 'gameover'); if (won) this.score += 1000 + this.lives * 150; const result = { won, reason, name: this.playerName, score: this.score, hits: this.hits, combo: this.bestCombo, lives: this.lives, accuracy: this.shots ? Math.round(this.hits / this.shots * 100) : 0 }; saveScore(result); setTimeout(() => this.onEnd(result), 650); }
  message(text) { const element = query('#game-message','#status-banner'); if (!element) return; element.textContent = text; element.classList.remove('show'); void element.offsetWidth; element.classList.add('show'); }
  shake() { this.screen.classList.remove('shake'); void this.screen.offsetWidth; this.screen.classList.add('shake'); }
  burst(x, y, color) { for (let i = 0; i < 12; i++) this.particles.push({ x, y, vx: (Math.random() - .5) * 180, vy: (Math.random() - .5) * 180, life: .5, color }); }
  updateHud(gaze) { const score=query('#score-value'); const hp=query('#boss-hp-bar','#hp-fill'); const lives=query('#lives-value'); const combo=query('#combo-value'); const gazeElement=query('#gaze-status','#status-banner'); if(score) score.textContent=String(this.score).padStart(6,'0'); if(hp) hp.style.width=`${Math.max(0,this.boss.hp/this.boss.maxHp*100)}%`; if(lives) lives.textContent='❤️ '.repeat(this.lives)+'🖤 '.repeat(3-this.lives); if(combo) combo.textContent=this.combo?`COMBO ×${this.combo}`:'COMBO BREAK'; if(gazeElement) gazeElement.textContent=`GAZE: ${gaze.state}`; }
  draw() { const context = this.ctx, width = this.canvas.width, height = this.canvas.height; context.clearRect(0, 0, width, height); const sky = context.createLinearGradient(0, 0, 0, height); sky.addColorStop(0, '#56c9e7'); sky.addColorStop(.64, '#a0e3d1'); sky.addColorStop(.641, '#7ed269'); context.fillStyle = sky; context.fillRect(0, 0, width, height); context.fillStyle = 'rgba(255,255,220,.8)'; for (let i = 0; i < 4; i++) { const x = ((i * 290 + this.last * .018) % (width + 200)) - 100; context.fillRect(x, 100 + (i % 2) * 55, 90, 18); context.fillRect(x + 20, 83 + (i % 2) * 55, 55, 35); } context.fillStyle = '#e49a3d'; for (let i = 0; i < 5; i++) context.fillRect(80 + i * 170, height * .52 + (i % 2) * 34, 75, 16); context.fillStyle = '#4fa84c'; context.fillRect(0, height * .72, width, height * .28); context.fillStyle = '#90633d'; for (let i = 0; i < 12; i++) context.fillRect(i * 90, height * .84 + (i % 3) * 13, 70, 45); context.fillStyle = '#f7ca45'; context.fillRect(this.mouse.x - 12, this.mouse.y - 1, 24, 2); context.fillRect(this.mouse.x - 1, this.mouse.y - 12, 2, 24); context.strokeStyle = '#142d4b'; context.strokeRect(this.mouse.x - 17, this.mouse.y - 17, 34, 34); this.boss?.draw(context); for (const projectile of this.projectiles) { context.strokeStyle = '#ffd447'; context.lineWidth = 4; context.beginPath(); context.moveTo(width * .5, height - 42); context.lineTo(projectile.x + (projectile.tx - width * .5) * projectile.t, projectile.y + (projectile.ty - (height - 42)) * projectile.t); context.stroke(); } for (const projectile of this.bossProjectiles) { context.fillStyle = '#f64d76'; context.fillRect(projectile.x - 12, projectile.y - 12, 24, 24); context.fillStyle = '#ffd447'; context.fillRect(projectile.x - 4, projectile.y - 4, 8, 8); } for (const particle of this.particles) { context.fillStyle = particle.color; context.fillRect(particle.x, particle.y, 5, 5); } }
  destroy() { this.running = false; this.canvas.removeEventListener('mousemove', this.move); window.removeEventListener('keydown', this.fire); window.removeEventListener('resize', this.resize); }
}
